### PR TITLE
Remove `location` key from examples

### PR DESCRIPTION
**Pull request by ericbiewener**

### CODE REVIEW

**Comment by ericbiewener** [comment]
@deepueg The link to sign the CLA has an empty "version" dropdown that doesn't let me proceed.

**Comment by deepueg** [comment]
@ericbiewener I noticed that it takes a while to load the version, can you please try again ?

**Review by deepueg — APPROVED** [review]
@ericbiewener Thanks for the PR.

**Review by friederbluemle — APPROVED** [review]
:+1:

**Pull request merged**
